openapi: 3.0.1
info:
  title: Car Hire API
  version: 0.1.0
  contact:
    name: Viorel Smeu
  description: Car Hire API
servers:
  - url: http://localhost:{port}
    description: local environment
    variables:
      port:
        default: '8080'
tags:
  - name: sample
    description: Sample resource endpoint
paths:
  /sample:
    get:
      tags:
        - sample
      summary: get sample
      description: returns a list of all the sample objects, without any filtering
      operationId: getSamples
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SampleDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'
  /fleet:
    post:
      tags:
        - fleet
        - sample
      summary: post fleet
      description: creates a new car for the fleet
      operationId: createCar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartDTO'
      responses:
        '201':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'
    get:
      tags:
        - fleet
      summary: get fleet
      description: gets the entire fleet, with filter options if specified
      operationId: getFleet
      parameters:
        - in: query
          name: status
          schema:
            type: string
          description: The status of the returned cars belonging to the fleet
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'
  /fleet/{carId}:
    get:
      tags:
        - fleet
      summary: get specific car from fleet
      description: retrieves a specific car from fleet based on its id
      operationId: getFleetCar
      parameters:
        - in: path
          name: carId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Id not found
        '500':
          $ref: '#/components/responses/ServerError'
    delete:
      tags:
        - fleet
      summary: deletes specific car from fleet
      description: deletes a specific car from fleet based on its id
      operationId: deleteFleetCar
      parameters:
        - in: path
          name: carId
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Deleted
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: id not found
        '500':
          $ref: '#/components/responses/ServerError'
    patch:
      tags:
        - fleet
      summary: updates a car properties
      description: updates a car properties
      operationId: patchFleetCar
      parameters:
        - in: path
          name: carId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchRequestDTO"
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartDTO'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: id not found
        '500':
          $ref: '#/components/responses/ServerError'


components:
  responses:
    Unauthorized:
      description: unauthorized
    BadRequest:
      description: bad request
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ValidationDTO'
    ServerError:
      description: internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
  schemas:
    ValidationDTO:
      type: object
      properties:
        code:
          type: string
        field:
          type: string
        description:
          type: string
    ErrorDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    SampleDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: id of the sample
        name:
          type: string
          example: Sample name
          description: full name of the sample
    CartDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: id of the car
        make:
          type: string
          description: make/brand of the car
        model:
          type: string
          description: model of the car
        year:
          type: string
          format: date
          description: the year when the car was fabricated
        mileage:
          type: integer
          format: int32
          description: the current mileage of the car
        fuel:
          type: string
          description: the fuel type of the car
        carClass:
          type: string
          description: the class of the car
        status:
          type: string
          enum: [ "ACTIVE", "DELETED" ]
          description: the status of the car
    PatchRequestDTO:
      type: array
      items:
        $ref: "#/components/schemas/PatchDocumentDTO"
    PatchDocumentDTO:
      description: A JSONPatch document as defined by RFC 6902
      required:
        - "operation"
        - "path"
      properties:
        operation:
          type: string
          description: The operation to be performed
          enum:
            - "add"
            - "remove"
            - "replace"
            - "move"
            - "copy"
            - "test"
        path:
          type: string
          description: A JSON-Pointer
        value:
          type: object
          description: The value to be used within the operations.
        from:
          type: string
          description: A string containing a JSON Pointer value.
